kibot:
  version: 1
global:
  out_dir: output
preflight:
  check_zone_fills: true
  erc: false
  drc: false
  update_stackup: true
  update_pcb_characteristics: true
  set_text_variables:
    # The revision will be the short git hash
    # We use ${git_hash} for the REV field in the worksheet (frame)
    - name: 'git_hash'
      command: 'git describe --always --tags --abbrev=20'
      before: 'Git: '

outputs:
  - name: Info
    type: info

  - name: Diff Schematic
    type: diff
    dir: sch
    options:
      only_different: true
      old: xxBASE
      pcb: false

  - name: Diff Layout
    type: diff
    dir: pcb
    options:
      only_different: true
      old: xxBASE
      pcb: true
